/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaccesscontrol.ui;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author Edwin Carmona
 */
public class CAPScreenLog extends javax.swing.JFrame {
    
    private List<CAPLogUI> lLog;
    private boolean autorization;
    
    /**
     * Creates new form CAPScreen
     */
    public CAPScreenLog() {
        initComponents();
        initCustom();
        autorization = false;
    }
    
    /**
     * Inicia objetos y componentes necesarios para el funcionamiento de la clase.
     */
    private void initCustom() {
        jTableLog.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableLog.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableLog.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTableLog.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableLog.getColumnModel().getColumn(4).setPreferredWidth(180);
        jTableLog.getColumnModel().getColumn(5).setPreferredWidth(180);
        jTableLog.getColumnModel().getColumn(6).setPreferredWidth(75);
        
        lLog = new ArrayList();
        
        String LAF = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        try {
            UIManager.setLookAndFeel(LAF);
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(CAPScreenLog.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            Logger.getLogger(CAPScreenLog.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            Logger.getLogger(CAPScreenLog.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CAPScreenLog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setSize(800, 500);
        SwingUtilities.updateComponentTreeUI(this);
        
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }
    
    /**
     * Actualizar bitácora.
     */
    public void updateTableLog() {
        CAPLogUIModel model = (CAPLogUIModel) jTableLog.getModel();
        
        if (300 < lLog.size()) {
            lLog.remove(lLog.size() - 1);
        }
        
        model.setlModelLog(lLog);
        model.fireTableDataChanged();
    }

    public List<CAPLogUI> getlLog() {
        return lLog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jScrollPanel = new javax.swing.JScrollPane();
        jTableLog = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Bitácora"));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel28.add(jLabel3);

        jPanel12.add(jPanel28, java.awt.BorderLayout.CENTER);

        jPanel31.setLayout(new java.awt.BorderLayout());

        jScrollPanel.setAutoscrolls(true);

        jTableLog.setModel(new CAPLogUIModel());
        jTableLog.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableLog.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPanel.setViewportView(jTableLog);
        jTableLog.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel31.add(jScrollPanel, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel31, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JTable jTableLog;
    // End of variables declaration//GEN-END:variables

}
